name: character_creator
description: "A role-playing game NPC creator."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_generative_ai: ^0.3.2
  google_fonts: ^6.2.1
  path: ^1.9.0
  path_provider: ^2.1.3
  url_launcher: ^6.2.5

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - 'assets/images/avatar.png'
